name: Release

on:
  push:
    tags:
      - '*' # Trigger the workflow on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare release directory
        run: |
          mkdir launcher_release
          cp -r assets mods config shaderpacks launcher_release/
          echo '{"version": "${{ github.ref_name }}" }' > launcher_release/assets/version.json
          cp launcher.py launcher_release/
          cp launcher launcher_release/
          cp launcher.jar launcher_release/
          cp requirements.txt launcher_release/
          cp servers.dat launcher_release/
          cp dist/launcher.exe launcher_release/
          cp servers.dat launcher_release/

      - name: Create Release
        id: create_release
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/releases
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Archive production
        run: |
          cd launcher_release
          zip -r ../launcher_release.zip *

      - name: Upload Release Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          upload_url: ${{ fromJson(steps.create_release.outputs.data).upload_url }}
          asset_path: ./launcher_release.zip
          asset_name: launcher_release.zip
          asset_content_type: application/zip
